### ISSUE TITLE
BasicFormatter.php: Unrecognised parameter page-count

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticNotifications#15]
### Setup and configuration

- SMW version: 2.5-alpha
- SNO version: 1.0-alpha
- MW version: all

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
2016-10-05 09:00:01 phalaris 0210020150926-02100_: [6233e93d678638d888c2814f] [no req]   MWException from line 883 of /var/www/htdocs/mw/02100/w/extensions/Echo/includes/formatters/BasicFormatter.php: Unrecognised parameter page-count
#0 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/formatters/EditFormatter.php(61): EchoBasicFormatter->processParam(EchoEvent, string, Message, User)
#1 /var/www/htdocs/mw/02100/w/extensions/SemanticNotifications/src/ChangeNotification/ChangeNotificationFormatter.php(26): EchoEditFormatter->processParam(EchoEvent, string, Message, User)
#2 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/formatters/BasicFormatter.php(632): SMW\Notifications\ChangeNotification\ChangeNotificationFormatter->processParam(EchoEvent, string, Message, User)
#3 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/formatters/BasicFormatter.php(332): EchoBasicFormatter->processParams(array, EchoEvent, Message, User)
#4 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/formatters/BasicFormatter.php(243): EchoBasicFormatter->formatFragment(array, EchoEvent, User)
#5 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/formatters/BasicFormatter.php(161): EchoBasicFormatter->formatEmail(EchoEvent, User, string)
#6 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/controller/NotificationController.php(412): EchoBasicFormatter->format(EchoEvent, User, string)
#7 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/Notifier.php(101): EchoNotificationController::formatNotification(EchoEvent, User, string, string)
#8 [internal function]: EchoNotifier::notifyWithEmail(User, EchoEvent)
#9 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/controller/NotificationController.php(279): call_user_func_array(array, array)
#10 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/controller/NotificationController.php(104): EchoNotificationController::doNotification(EchoEvent, User, string)
#11 /var/www/htdocs/mw/02100/w/extensions/Echo/includes/model/Event.php(155): EchoNotificationController::notify(EchoEvent, boolean)
#12 /var/www/htdocs/mw/02100/w/extensions/SemanticNotifications/src/EchoNotificationsManager.php(177): EchoEvent::create(array)
#13 /var/www/htdocs/mw/02100/w/extensions/SemanticNotifications/src/HookRegistry.php(165): SMW\Notifications\EchoNotificationsManager->createEvent(array)
#14 [internal function]: SMW\Notifications\HookRegistry->SMW\Notifications\{closure}(SMWSQLStore3, SMW\SemanticData, SMW\SQLStore\CompositePropertyTableDiffIterator)
#15 /var/www/htdocs/mw/02100/w/includes/Hooks.php(195): call_user_func_array(Closure, array)
#16 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Writers.php(173): Hooks::run(string, array)
#17 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(347): SMWSQLStore3Writers->doDataUpdate(SMW\SemanticData)
#18 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(250): SMWSQLStore3->doDataUpdate(SMW\SemanticData)
#19 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/StoreUpdater.php(192): SMW\Store->updateData(SMW\SemanticData)
#20 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/StoreUpdater.php(126): SMW\StoreUpdater->doRealUpdate()
#21 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/StoreUpdater.php(92): SMW\StoreUpdater->performUpdate()
#22 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/includes/ParserData.php(296): SMW\StoreUpdater->doUpdate()
#23 [internal function]: SMW\ParserData->SMW\{closure}()
#24 /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/src/DeferredCallableUpdate.php(119): call_user_func(Closure)
#25 /var/www/htdocs/mw/02100/w/includes/deferred/DeferredUpdates.php(151): SMW\DeferredCallableUpdate->doUpdate()
#26 /var/www/htdocs/mw/02100/w/includes/deferred/DeferredUpdates.php(88): DeferredUpdates::execute(array, string)
#27 /var/www/htdocs/mw/02100/w/includes/jobqueue/JobRunner.php(269): DeferredUpdates::doUpdates()
#28 /var/www/htdocs/mw/02100/w/includes/jobqueue/JobRunner.php(179): JobRunner->executeJob(RefreshLinksJob, BufferingStatsdDataFactory, integer)
#29 /var/www/htdocs/mw/02100/w/maintenance/runJobs.php(93): JobRunner->run(array)
#30 /var/www/htdocs/mw/02100/w/maintenance/doMaintenance.php(103): RunJobs->execute()
#31 /var/www/htdocs/mw/02100/w/maintenance/runJobs.php(127): require_once(string)
#32 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

**Comment by mwjames** [comment]
@kghbln FYI Removed the alleged `page-count` parameter.
