### ISSUE TITLE
Error from line 266 of "ChangeNotificationFilter.php"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticNotifications#27]
### Setup and configuration

- MediaWiki | 1.32.1 (7908476)05:26, 26. Mär. 2019
- Semantic MediaWiki | 3.1.0-alpha (f5fde17) 20:41, 1. Apr. 2019
- Semantic Notifications | 1.0.0-alpha (27ba1f7) 02:26, 16. Sep. 2018

### Issue

```
[93e373d6df759c3b8f615587] /w/index.php?title=PageID&action=submit Error from line 266 of /.../w/extensions/SemanticNotifications/src/ChangeNotification/ChangeNotificationFilter.php: Call to undefined method SMW\ApplicationFactory::getCachedPropertyValuesPrefetcher()
```

### Backtrace
```
#0 /.../w/extensions/SemanticNotifications/src/ChangeNotification/ChangeNotificationFilter.php(259): SMW\Notifications\ChangeNotification\ChangeNotificationFilter->doCompareNotificationsOnValuesWithOps(SMW\DIProperty, SMW\DIWikiPage, SMW\SQLStore\ChangeOp\FieldChangeOp)
#1 /.../w/extensions/SemanticNotifications/src/ChangeNotification/ChangeNotificationFilter.php(200): SMW\Notifications\ChangeNotification\ChangeNotificationFilter->doFilterOnFieldChangeOps(SMW\DIProperty, SMW\SQLStore\ChangeOp\TableChangeOp, array)
#2 /.../w/extensions/SemanticNotifications/src/ChangeNotification/ChangeNotificationFilter.php(135): SMW\Notifications\ChangeNotification\ChangeNotificationFilter->hasChangeToNotifyAbout(SMW\SQLStore\ChangeOp\ChangeOp)
#3 /.../w/extensions/SemanticNotifications/src/HookRegistry.php(172): SMW\Notifications\ChangeNotification\ChangeNotificationFilter->findChangeEvent(SMW\SQLStore\ChangeOp\ChangeOp)
#4 /.../w/includes/Hooks.php(174): SMW\Notifications\HookRegistry->SMW\Notifications\{closure}(SMWSQLStore3, SMW\SemanticData, SMW\SQLStore\ChangeOp\ChangeOp)
#5 /.../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#6 /.../w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Writers.php(261): Hooks::run(string, array)
#7 /.../w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(290): SMWSQLStore3Writers->doDataUpdate(SMW\SemanticData)
#8 /.../w/extensions/SemanticMediaWiki/src/Store.php(237): SMWSQLStore3->doDataUpdate(SMW\SemanticData)
#9 /.../w/extensions/SemanticMediaWiki/src/DataUpdater.php(396): SMW\Store->updateData(SMW\SemanticData)
#10 /.../w/extensions/SemanticMediaWiki/src/DataUpdater.php(282): SMW\DataUpdater->updateData()
#11 /.../w/extensions/SemanticMediaWiki/src/DataUpdater.php(200): SMW\DataUpdater->performUpdate()
#12 [internal function]: SMW\DataUpdater->SMW\{closure}()
#13 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(225): call_user_func(Closure)
#14 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/TransactionalCallableUpdate.php(168): SMW\MediaWiki\Deferred\CallableUpdate->doUpdate()
#15 /.../w/includes/deferred/DeferredUpdates.php(270): SMW\MediaWiki\Deferred\TransactionalCallableUpdate->doUpdate()
#16 /.../w/includes/deferred/DeferredUpdates.php(216): DeferredUpdates::runUpdate(SMW\MediaWiki\Deferred\TransactionalCallableUpdate, Wikimedia\Rdbms\LBFactorySimple, string, integer)
#17 /.../w/includes/deferred/DeferredUpdates.php(140): DeferredUpdates::execute(array, string, integer)
#18 /.../w/includes/MediaWiki.php(903): DeferredUpdates::doUpdates(string)
#19 /.../w/includes/MediaWiki.php(726): MediaWiki->restInPeace(string, boolean)
#20 /.../w/includes/MediaWiki.php(749): MediaWiki->{closure}()
#21 /.../w/includes/MediaWiki.php(550): MediaWiki->doPostOutputShutdown(string)
#22 /.../w/index.php(42): MediaWiki->run()
#23 {main}
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

This happens on action submit.

**Comment by mwjames** [comment]
> [93e373d6df759c3b8f615587] /w/index.php?title=PageID&action=submit Error
> from line 266 of
> /.../w/extensions/SemanticNotifications/src/ChangeNotification/ChangeNotificationFilter.php:
> Call to undefined method
> SMW\ApplicationFactory::getCachedPropertyValuesPrefetcher()

Yes, this relates to
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3877. I
thought I got them all.

Here is what needs to be fixed:

Replace:

`$cachedPropertyValuesPrefetcher =
ApplicationFactory::getInstance()->getCachedPropertyValuesPrefetcher();`

with

`$propertySpecificationLookup =
ApplicationFactory::getInstance()->getPropertySpecificationLookup();

and

`if ( ( $pv = $cachedPropertyValuesPrefetcher->getPropertyValues(
$dataItem, $property ) ) !== array() ) {`

with

`if ( ( $pv = $propertySpecificationLookup->getSpecification(
$dataItem, $property ) ) !== array() ) {`

Cheers

**Comment by kghbln** [comment]
Thanks for the info. Will do a pull soon.
